name: ace_dicoding_ahmad
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.2
  flutter_svg: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.8
  flutter_gen_runner: ^4.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/socmed/